name: Deploy Docker to EC2

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: develop

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_KEY }}" > ~/.ssh/id_rsa.pem
          chmod 600 ~/.ssh/id_rsa.pem
          ssh-keyscan -H ${{ secrets.EC2_HOST }} >> ~/.ssh/known_hosts
          echo "Host *" >> ~/.ssh/config
          echo "  StrictHostKeyChecking no" >> ~/.ssh/config
          echo "  UserKnownHostsFile ~/.ssh/known_hosts" >> ~/.ssh/config

      - name: Copy project to EC2
        run: |
          rsync -avz -e "ssh -i ~/.ssh/id_rsa.pem" ./ ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }}:${{ secrets.APP_DIR }}
          echo "${{ secrets.EC2_KEY }}"
          echo "${{ secrets.EC2_USER }}"
          echo "${{ secrets.EC2_HOST }}"
          echo "${{ secrets.APP_DIR }}"

      # - name: Create .env on EC2
      #   run: |
      #     ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
      #       cat > ${{ secrets.APP_DIR }}/.env << EOL
      #       PORT=${{ secrets.ENV_PORT }}
      #       DB_URL=${{ secrets.ENV_DB_URL }}
      #       JWT_SECRET=${{ secrets.ENV_JWT_SECRET }}
      #       # Add more variables as needed
      #       EOL
      #     EOF

      - name: Build & Run Docker on EC2
        run: |
          ssh ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            cd ${{ secrets.APP_DIR }}
            docker stop my-app || true && docker rm my-app || true
            docker build -t my-app .
            docker run -d -p 80:3000 --env-file .env --name my-app my-app
          EOF
